### ISSUE TITLE
KeyError: 'task_id'

### ISSUE THREAD

**Issue by sherlcok314159** [HKUNLP/instructor-embedding#21]
Hi! I am trying to train instructor-embedding and come up with the error shown in the title. More specifically, 

```bash
Traceback (most recent call last):
  File "train.py", line 577, in <module>
    main()
  File "train.py", line 450, in main
    print(f'one batch in task {old_train_examples_raw[idx1]["task_id"]} is skipped')
KeyError: 'task_id'
```

I have downloaded data and put them right in the `cache_dir`. And here is my running script:

```bash
# train the model
model_name=hkunlp/instructor-base
sentence_model_name=sentence-transformers/gtr-t5-base
output_dir=outputs
data_dir=medi-data

python train.py \
    --model_name_or_path=${sentence_model_name} \
    --output_dir=${output_dir} \
    --cache_dir=${data_dir} \
    --max_source_length=512 \
    --num_train_epochs=10 \
    --save_steps=500 \
    --cl_temperature=0.01 \
    --warmup_ratio=0.1 \
    --learning_rate=2e-5 \
    --overwrite_output_dir
```

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in INSTRUCTOR!

We fixed the typo in train.py. Please try again!

**Comment by sherlcok314159** [comment]
Thanks for your quick reply. It works.
